image: alpine

pages:
  script:
  - apk --no-cache add py3-pip python3-dev gcc make
  - pip3 install --upgrade pip
  - pip3 install -r dev_requirements.txt
  - apk --no-cache add make
  - cd docs
  - make html
  - mv _build/ public/
  artifacts:
    paths:
    - public
  only:
  - master
