image: python:3.7.3-alpine

pages:
  script:
  - pip install -r dev_requirements.txt
  - apk --no-cache add make
  - cd docs
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
