image: python:3.7.3-slim-stretch

pages:
  script:
  - apt install python3-pip python3-dev build-essentials
  - pip3 install --upgrade pip
  - pip3 install -r dev_requirements.txt
  - cd docs
  - make html
  - mv _build/ public/
  artifacts:
    paths:
    - public
  only:
  - master
