image: python:3.7.3-alpine

pages:
  script:
  - apk --no-cache add make gcc musl-dev
  - pip install -r dev_requirements.txt
  - pip install -r requirements.txt
  - cd docs
  - make html
  - mv _build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
